services:
  postgres:
    ports:
      - "5432:5432"

  backend:
    ports:
      - "8000:8000"
    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"

  frontend:
    ports:
      - "80:4173"
    command: sh -c "npm run build && npm run preview --host"
