"""progress filed index

Revision ID: 19048fef7aa1
Revises: 96329daf32ba
Create Date: 2025-03-24 05:21:30.736868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19048fef7aa1'
down_revision: Union[str, None] = '96329daf32ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('index_jobs', sa.Column('progress', sa.Float(), nullable=True))
    op.create_unique_constraint(None, 'token_blacklist', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'token_blacklist', type_='unique')
    op.drop_column('index_jobs', 'progress')
    # ### end Alembic commands ###
