"""add_cascade_delete_to_index_jobs

Revision ID: ddc33d0d8eae
Revises: dd805797852c
Create Date: 2025-03-20 08:44:57.977293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ddc33d0d8eae'
down_revision: Union[str, None] = 'dd805797852c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('index_jobs')
    op.drop_index('ix_industry_indexes_id', table_name='industry_indexes')
    op.drop_index('ix_industry_indexes_industry_id', table_name='industry_indexes')
    op.drop_table('industry_indexes')
    op.create_unique_constraint(None, 'token_blacklist', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'token_blacklist', type_='unique')
    op.create_table('industry_indexes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('industry_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('index_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cached_data_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('embeddings_model', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('reviews_included', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], name='industry_indexes_industry_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='industry_indexes_pkey')
    )
    op.create_index('ix_industry_indexes_industry_id', 'industry_indexes', ['industry_id'], unique=True)
    op.create_index('ix_industry_indexes_id', 'industry_indexes', ['id'], unique=False)
    op.create_table('index_jobs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('industry_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('error', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('reviews_included', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], name='index_jobs_industry_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='index_jobs_pkey')
    )
    # ### end Alembic commands ###
